function T=transformacion(X0,Y0,alfa)
T=[ cos(alfa)    -sin(alfa)    0       X0;...
    sin(alfa)     cos(alfa)    0       Y0; ...
    0               0          1        0; ...
    0               0          0        1];
end